### ISSUE TITLE
ERC1155U/ERC1155D

### ISSUE THREAD

**Issue by transmissions11** [Rari-Capital/solmate#189]
https://etherscan.io/address/0xe76512732b1e49eb259dfc6d9d49e4c5dac6a75c#code

https://github.com/DonkeVerse/ERC1155D

**Comment by PraneshASP** [comment]
Hi @transmissions11 not sure if this is the correct place for this discussion. 

Just curios to know why the `isApprovedForAll` check is ignored in the `burn()` method of  the [**Solmate's ERC1155 library**](https://github.com/Rari-Capital/solmate/blob/main/src/tokens/ERC1155.sol). Is it due to the reason that the validation can be done in the implementation contract? or is it safe to ignore the check completely?

```console
1) Contract: ERC1155Burnable
       burn
         unapproved accounts cannot burn the holder's tokens:
     AssertionError: Expected an exception but none was received
```


Because the testcases(based on OZ tests) are being reverted at the `burn` and `batchBurn` methods. Fixed the above issue by adding the validation in the implementing contract, but just wanted to check this with you as well.

Kindly advise.

Cheers!

**Comment by transmissions11** [comment]
its an internal burn function, if the developer wishes to expose a public burn they must implement that behavior themselves
