### ISSUE TITLE
ERC20.transferFrom() deducting allowance from sender

### ISSUE THREAD

**Issue by BDANG** [Rari-Capital/solmate#87]
https://github.com/Rari-Capital/solmate/blob/fab107565a51674f3a3b5bfdaacc67f6179b1a9b/src/tokens/ERC20.sol#L91-L98

Not sure if there is a security reason for this, but I wonder if `allowance[from][msg.sender] -= amount` should be `allowance[from][to] -= amount` instead.

I came across this issue from testing a contract that calls `transferFrom` on behalf of different contract. The idea is the contract is handling some book keeping logic but the other contract is responsible for handling and managing the funds

Example:
```
// approval submitted by the user to allow their balance to be deducted by `parentContract`
// ERC20.approve(parentContractAddress, 90);

contract externalContract {
  function deposit(uint256 amount){
    // check allowance etc
    // other logic

    token = IERC20(...)
    token.transferFrom(msg.sender, parentContractAddress, amount);
  }
}
```

**Comment by transmissions11** [comment]
heyo!

no, `to` is not necessarily the caller of transferFrom. if their allowance was checked instead of `msg.sender` anyone could frontrun transferFroms by calling it themselves right after an approvals :)

see OpenZeppelin and Uniswap as further evidence this is the correct implementation:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/1ffcb10bd2219c850ebbc56030fa946a84963215/contracts/token/ERC20/ERC20.sol#L157

https://github.com/Uniswap/v2-core/blob/master/contracts/UniswapV2ERC20.sol#L75
